"""user_addColumn_nickname

Revision ID: 507b41300e6e
Revises: 134d40f22e3b
Create Date: 2018-08-07 22:49:40.155755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507b41300e6e'
down_revision = '134d40f22e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###
