"""user_addColumu_bbb

Revision ID: 6a3e691183b9
Revises: 507b41300e6e
Create Date: 2018-08-07 23:03:54.208604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3e691183b9'
down_revision = '507b41300e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bbb', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'users', ['bbb'])  # 生成唯一性约束
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'users', type_='unique') # 自动生成，需要手动修改
    op.drop_constraint('bbb', 'users', type_='unique')  # 删除唯一约束
    op.drop_column('users', 'bbb')
    # ### end Alembic commands ###
